import { testRegistry } from '../../lib/tests/test-registry';

/**
 * Cloudflare Pages Function for dynamic share page with OG metadata
 *
 * ビルド済みの静的HTMLを読み込み、OGメタタグだけを動的に書き換えます。
 * これにより、Next.jsの美しいUIを保ちつつ、SNSクローラーには正しいOG画像を返せます。
 */
export const onRequest: PagesFunction<{ test: string }> = async (context) => {
  const { test } = context.params;
  const testString = Array.isArray(test) ? test[0] : test;
  const url = new URL(context.request.url);

  // Get config from test registry
  const config = testRegistry[testString as keyof typeof testRegistry];

  if (!config?.ogImage) {
    return new Response('Test not found', { status: 404 });
  }

  const { ogImage } = config;

  // クエリパラメータからスコアを復元
  let ogImageUrl = `/og/${testString}`;
  if (ogImage.scoreToParams && url.searchParams.toString()) {
    // パラメータが存在する場合、OG画像URLにそのまま付与
    ogImageUrl = `/og/${testString}?${url.searchParams.toString()}`;
  }

  // 絶対URLに変換（OGメタタグには絶対URLが必要）
  const origin = url.origin;
  const fullOgImageUrl = `${origin}${ogImageUrl}`;
  const fullShareUrl = url.toString();

  // ビルド済みの静的HTMLを読み込む
  const staticHtmlPath = `/share/${testString}/index.html`;
  const staticHtmlResponse = await context.env.ASSETS.fetch(new Request(`${origin}${staticHtmlPath}`));

  if (!staticHtmlResponse.ok) {
    return new Response('Page not found', { status: 404 });
  }

  let html = await staticHtmlResponse.text();

  // OGメタタグを動的に置換
  // 既存のOGメタタグを削除
  html = html.replace(/<meta property="og:image"[^>]*>/gi, '');
  html = html.replace(/<meta property="og:image:width"[^>]*>/gi, '');
  html = html.replace(/<meta property="og:image:height"[^>]*>/gi, '');
  html = html.replace(/<meta name="twitter:image"[^>]*>/gi, '');

  // 動的OGメタタグを挿入（</head>の直前）
  const ogTags = `
  <!-- Dynamic OG tags (generated by Cloudflare Function) -->
  <meta property="og:image" content="${fullOgImageUrl}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:image" content="${fullOgImageUrl}">
</head>`;

  html = html.replace('</head>', ogTags);

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
    },
  });
};
